apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
<<<<<<< HEAD
  rmq-pass: Z3Vlc3Q=
=======
  rmq-pass: Z3Vlc3Q=
>>>>>>> b633b77de6d6cfab41d4b7ab7c061f4ed503c70e
